# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVN-RaWeb-Light
version:      0.2.1
version_from: lib/SVN/RaWeb/Light.pm
installdirs:  site
requires:
    CGI:                           0
    SVN::Ra:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
