---
abstract: "Lightweight and Fast Browser for a URLed Subversion \nrepository similar to the default Subversion http:// hosting."
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
build_requires:
  Test::More: 0
  base: 0
  strict: 0
  warnings: 0
configure_requires:
  File::Spec: 0
  Module::Build: 0.36
  lib: 0
generated_by: 'Module::Build version 0.3617'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-RaWeb-Light
provides:
  SVN::RaWeb::Light:
    file: lib/SVN/RaWeb/Light.pm
    version: 0.60001
  SVN::RaWeb::Light::Help:
    file: lib/SVN/RaWeb/Light/Help.pm
requires:
  CGI: 0
  Class::Accessor: 0
  IO::Scalar: 0
  SVN::Core: 0
  SVN::Ra: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
version: 0.60001
