---
abstract: 'Lightweight and Fast Browser for a URLed Subversion'
author:
  - 'Shlomi Fish'
build_requires:
  Test::More: '0'
  base: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  File::Spec: '0'
  Module::Build: '0.36'
  lib: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
keywords:
  - browser
  - light
  - subversion
  - vcs
  - web
  - www
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SVN-RaWeb-Light
provides:
  SVN::RaWeb::Light:
    file: lib/SVN/RaWeb/Light.pm
    version: '0.60005'
requires:
  CGI: '0'
  Class::Accessor: '0'
  IO::Scalar: '0'
  SVN::Core: '0'
  SVN::Ra: '0'
  perl: '5.008'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  homepage: http://web-cpan.shlomifish.org/modules/SVN-RaWeb-Light/
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://bitbucket.org/shlomif/perl-svn-raweb-light
version: '0.60005'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
