---
name: SVN-RaWeb-Light
version: 0.6.0
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
abstract: |-
  Lightweight and Fast Browser for a URLed Subversion 
  repository similar to the default Subversion http:// hosting.
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
requires:
  CGI: 0
  Class::Accessor: 0
  IO::Scalar: 0
  SVN::Ra: 0
  Test::More: 0
provides:
  SVN::RaWeb::Light:
    file: lib/SVN/RaWeb/Light.pm
    version: 0.6.0
  SVN::RaWeb::Light::Help:
    file: lib/SVN/RaWeb/Light/Help.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
